// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIThFBMBpmGHcN7i5tWz2l2_bL97IpAPw',
    appId: '1:101162702418:android:281afdce1bdb7df69ff18b',
    messagingSenderId: '101162702418',
    projectId: 'flutter-chatty-8cc59',
    storageBucket: 'flutter-chatty-8cc59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFEoqzTJWjzFqZk4Nib4i5YNVZL-PTACo',
    appId: '1:101162702418:ios:c5673c27956d48339ff18b',
    messagingSenderId: '101162702418',
    projectId: 'flutter-chatty-8cc59',
    storageBucket: 'flutter-chatty-8cc59.appspot.com',
    androidClientId: '101162702418-vrpthfote9cmq0n5ukb4rjc11pq6ee6s.apps.googleusercontent.com',
    iosClientId: '101162702418-f85nuupeesvcvgdnaoa2610ktm6n0fvr.apps.googleusercontent.com',
    iosBundleId: 'com.bhautik.chatty',
  );
}
